/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#b7c4ff",
        "surface": "var(--color-surface)",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#858690",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container-lowest": "var(--color-pure-white)",
        "tertiary-container": "#251e13",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "inverse-surface": "#2e3132",
        "primary-container": "#1d1f27",
        "on-primary-fixed": "#191b23",
        "primary-fixed": "#e1e2ed",
        "on-secondary": "#ffffff",
        "surface-variant": "var(--color-surface-container-high)",
        "background": "var(--color-background)",
        "secondary-fixed": "#dde1ff",
        "surface-container": "var(--color-surface-container)",
        "on-tertiary-fixed": "#211b10",
        "on-secondary-fixed-variant": "#113aaf",
        "on-tertiary-fixed-variant": "#4e4538",
        "primary-fixed-dim": "#c5c6d1",
        "surface-container-high": "var(--color-surface-container-high)",
        "inverse-on-surface": "#f0f1f3",
        "on-secondary-container": "#002074",
        "on-error": "#ffffff",
        "inverse-primary": "#c5c6d1",
        "outline": "#77767c",
        "on-primary-fixed-variant": "#45464f",
        "on-background": "var(--color-on-surface)",
        "pure-white": "var(--color-pure-white)",
        "white": "var(--color-pure-white)",
        "outline-variant": "#c7c6cb",
        "error-container": "#ffdad6",
        "secondary-container": "#6b89fe",
        "surface-alt": "var(--color-surface)",
        "surface-bright": "var(--color-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-tertiary-container": "#908576",
        "surface-tint": "#5c5e67",
        "error": "#ba1a1a",
        "border-subtle": "var(--color-border-subtle)",
        "tertiary-fixed": "#efe0cf",
        "on-surface": "var(--color-on-surface)",
        "on-secondary-fixed": "#001453",
        "tertiary": "#0a0601",
        "tertiary-fixed-dim": "#d2c5b3",
        "primary": "var(--color-primary)",
        "secondary": "var(--color-secondary)",
        "surface-dim": "var(--color-surface-container-high)"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-desktop": "64px",
        "container-max": "1280px",
        "unit": "8px",
        "gutter": "24px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "headline-md": ["Hanken Grotesk"],
        "label-sm": ["Hanken Grotesk"],
        "body-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        "headline-xl": ["Hanken Grotesk"],
        "headline-xl-mobile": ["Hanken Grotesk"]
      },
      fontSize: {
        "headline-md": ["24px", {"lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-xl": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.03em", "fontWeight": "700"}],
        "headline-xl-mobile": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    }
  },
  plugins: [],
}
